name: ci/gh-actions/build

on:
  push:
    branches: [master, main, dev]
  pull_request:

jobs:
  build-ubuntu-without-scanner:
    name: "Ubuntu 24.04 (no scanner)"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - name: update apt
        run: apt update
      - name: install dependencies
        run: |
          apt -y install git cmake build-essential ccache libssl-dev libunbound-dev libboost-all-dev \
          libqrencode-dev qt6-base-dev qt6-svg-dev qt6-websockets-dev qt6-multimedia-dev \
          qt6-wayland-dev libzip-dev libsodium-dev libgcrypt20-dev libx11-xcb-dev \
          protobuf-compiler libprotobuf-dev libhidapi-dev libzxing-dev libusb-dev \
          libusb-1.0-0-dev
      - name: configure git
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        run: |
          mkdir build
          cd build
          cmake -DWITH_SCANNER=OFF ..
          cmake --build . -j $(nproc)

  build-ubuntu-22:
    name: "Ubuntu 22.04 (Qt 5.15)"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: update apt
        run: apt update
      - name: install dependencies
        # FIXED: Switched to native Qt5 packages because Qt6 is incomplete on 22.04
        run: |
          apt -y install git cmake build-essential ccache libssl-dev libunbound-dev \
          libboost-all-dev libqrencode-dev qtbase5-dev libqt5svg5-dev libqt5websockets5-dev \
          qtmultimedia5-dev libzip-dev libsodium-dev libgcrypt20-dev libx11-xcb-dev \
          protobuf-compiler libprotobuf-dev libhidapi-dev libusb-dev libusb-1.0-0-dev
      - name: configure git
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        run: |
          mkdir build
          cd build
          cmake -DWITH_SCANNER=OFF ..
          cmake --build . -j $(nproc)

  build-ubuntu-20:
    name: "Ubuntu 20.04 (Default Qt 5.12)"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: update apt
        run: apt update
      - name: install dependencies
        run: |
          apt -y install git cmake build-essential ccache libssl-dev libunbound-dev \
          libboost-all-dev libqrencode-dev qtbase5-dev libqt5svg5-dev libqt5websockets5-dev \
          qtmultimedia5-dev libzip-dev libsodium-dev libgcrypt20-dev libx11-xcb-dev \
          protobuf-compiler libprotobuf-dev libhidapi-dev libusb-dev libusb-1.0-0-dev
      - name: configure git
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        run: |
          mkdir build
          cd build
          cmake -DWITH_SCANNER=OFF ..
          cmake --build . -j $(nproc)

  build-arch:
    name: "Arch Linux"
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: install dependencies
        run: pacman -Syyu --noconfirm git cmake base-devel unbound boost qrencode qt6-base qt6-svg qt6-websockets qt6-wayland qt6-multimedia libzip hidapi protobuf zxing-cpp
      - name: configure git
        run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        run: |
          cmake -S . -B build
          cmake --build build -j $(nproc)

  build-macos:
    name: "macOS (brew)"
    if: false
    runs-on: macos-latest
    env:
      CCACHE_DIR: /Users/runner/Library/Caches/ccache
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          brew install --quiet qt libsodium libzip qrencode unbound cmake boost hidapi openssl expat protobuf pkg-config ccache ninja
      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: macos-ccache-${{ github.sha }}
          restore-keys: |
            macos-ccache-
      - name: build
        run: |
          cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release -DWITH_SCANNER=Off -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build build
