name: macOS CI

on:
  push:
    tags:
      - "macos-2.8.1-*"

jobs:
  build:
    name: macOS (brew)
    runs-on: macos-latest
    steps:
    env:
      CCACHE_DIR: /Users/runner/Library/Caches/ccache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew update
          brew install --quiet qt libsodium libzip qrencode unbound cmake boost hidapi openssl expat protobuf pkg-config ccache

      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: macos-ccache-${{ github.sha }}
          restore-keys: |
            macos-ccache-

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DWITH_SCANNER=OFF -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build build -j $(sysctl -n hw.ncpu)

      - name: Validate Version
        run: ./build/bin/feather.app/Contents/MacOS/feather --version
